# Generated by Django 6.0 on 2026-01-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
    ]
